baseURL = "https://mcbianconi.com/"

languageCode = "pt-br"
enableRobotsTXT = true
paginate = 10

defaultContentLanguage = "pt-br"

summaryLength = 0

[outputs]
home = ["HTML"
    # , "RSS"
    # , "JSON"
]

[languages.en]
contentDir = "content/en"

[languages.pt-br]
contentDir = "content"