baseURL = "https://mcbianconi.com/"

languageCode = "pt-BR"
enableRobotsTXT = true
paginate = 10

summaryLength = 0

[outputs]
home = ["HTML"
    # , "RSS"
    # , "JSON"
]


[languages]

  [languages.pt-BR]
    contentDir = 'content/pt-BR'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    weight = 1
    # [languages.pt-BR.params]
    #   subtitle = 'Reference, Tutorials, and Explanations'

  [languages.en]
      contentDir = 'content/en'
  #     disabled = false
  #     languageCode = 'en'
  #     weight = 2
  #     [languages.en.params]
  #       subtitle = 'Referenz, Tutorials und Erklärungen'