languageCode = "pt-br"
languageName = "Português"
weight = 1
title = "MCBianconi"

[params]
  displayName = "PT/BR"
  isoCode = "pt-BR"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Murillo Cesar Bianconi"
  image = "img/blowfish_logo.png"
  headline = "Em uma missão"
  bio = "Em uma missão"
  links = [
    { github = "https://github.com/mcbianconi" },
    { linkedin = "https://linkedin.com/in/mcbianconi" },
]
