[[main]]
 name = "Blog"
 pageRef = "blog"
 weight = 1

[[main]]
 name = "Projetos"
 pageRef = "categories/projetos"
 weight = 2


[[main]]
 name = "Tarô"
 pageRef = "tarot"
 weight = 3

 [[main]]
 name = "Tiragem diária"
 parent = "Tarô"
 pageRef = "categories/tarô-do-dia"
 weight = 3

 [[main]]
 name = "Sobre mim"
 pageRef = "sobre-mim"
 weight = 4


[[subnavigation]]
 name = "Tecnologia"
 pre = "github"
 pageRef = "tags/tech"
 weight = 1

 [[subnavigation]]
 name = "Tarô"
 pageRef = "tarot"
 weight = 2

[[subnavigation]]
 name = "Pensamentos"
 pageRef = "tags/pensamentos"
 weight = 3

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "/tags"
  weight = 10

[[footer]]
  name = "Categorias"
  pageRef = "/categories"
  weight = 20
